In [ ]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
arr=np.array([45,67,78,89])
arr

array([45, 67, 78, 89])

In [ ]:
1,2,3,....ndim

In [21]:
arr1=np.array([[[23,45,67],[78,9,9],[7,6,5]]])
print(arr1)
print(arr1.ndim)

[[[23 45 67]
  [78  9  9]
  [ 7  6  5]]]
3


In [23]:
num=np.ones((2,3))
num

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
num=np.eye(4)
num

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
num=np.arange(0,10,2)
num

array([0, 2, 4, 6, 8])

In [40]:
num=np.linspace(11,20,5)
num

array([11.  , 13.25, 15.5 , 17.75, 20.  ])

In [46]:
num=np.random.rand(2,3)
num

array([[0.48380709, 0.97819013, 0.14950172],
       [0.81739459, 0.97388482, 0.73733737]])

In [48]:
num=np.full((2,2),7)
num

array([[7, 7],
       [7, 7]])

In [54]:
num=np.empty((2,2))
num

array([[1., 1.],
       [1., 1.]])

In [62]:
num.itemsize

8

In [77]:
names=np.array([[["joe","krish","maya","zoya"],["joe","krish","maya","zoya"]],
                [["joe","krish","maya","zoya"],["joe","krish","maya","zoya"]]])
names

array([[['joe', 'krish', 'maya', 'zoya'],
        ['joe', 'krish', 'maya', 'zoya']],

       [['joe', 'krish', 'maya', 'zoya'],
        ['joe', 'krish', 'maya', 'zoya']]], dtype='<U5')

In [57]:
names.shape

(2, 4)

In [58]:
names.size

8

In [59]:
names.dtype

dtype('<U5')

In [64]:
names.nbytes

160

In [65]:
names.T

array([['joe', 'joe'],
       ['krish', 'krish'],
       ['maya', 'maya'],
       ['zoya', 'zoya']], dtype='<U5')

In [68]:
list(names.flat)

['joe', 'krish', 'maya', 'zoya', 'joe', 'krish', 'maya', 'zoya']

In [69]:
names

array([['joe', 'krish', 'maya', 'zoya'],
       ['joe', 'krish', 'maya', 'zoya']], dtype='<U5')

In [70]:
rea=np.array([2+4j,9+5j])
rea

array([2.+4.j, 9.+5.j])

In [71]:
rea.real

array([2., 9.])

In [73]:
rea.imag

array([4., 5.])

In [74]:
names.data